/**
 * GetLimit DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: limits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetLimitPackageParams } from "@ordovex/core/limits";

export function createGetLimitRequest(overrides: Partial<GetLimitPackageParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
