/**
 * Handlers for Pack
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incidents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { IncidentsDomainModule } from "../dependencies/incidents-ddd.dependencies.js";
import type { CreateIncidentPackInput, GetIncidentPackInput, ListIncidentPacksInput } from "@ordovex/services/incidents";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/incidents/packs
 * Operation: listIncidentPacks
 */
export async function listIncidentPacks(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], strategyId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: IncidentsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListIncidentPacksInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.packs.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/incidents/packs
 * Operation: createIncidentPack
 */
export async function createIncidentPack(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: IncidentsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateIncidentPackInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.packs.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/incidents/packs/{incidentPackId}
 * Operation: getIncidentPack
 */
export async function getIncidentPack(
  request: FastifyRequest<{ Params: { incidentPackId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: IncidentsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetIncidentPackInput = {
    incidentPackId: request.params.incidentPackId,
  };
  const result = await deps.useCases.packs.get.execute(input);
  return reply.code(200).send(result);
}


