/**
 * SimulateTightest DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: limits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SimulateTightest DTOs
 *
 * DDD: Application DTOs for SimulateTightest use cases.
 */

import type { SimulateTightestWinsParams } from "@ordovex/core/limits/types";

export type SimulateTightestWinsInput = SimulateTightestWinsParams;

export type SimulateTightestWinsOutput = {};
