/**
 * ExecuteGetControlPlaneHealth - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: health
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetControlPlaneHealth Use Case
 *
 * DDD: Application use case for get ControlPlane.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetControlPlaneHealthInput, GetControlPlaneHealthOutput } from "../dto/control-plane.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ordovex/services/_shared/index.js";
import type { ControlPlaneRepository } from "../ports";
import { NotFoundError } from "../errors";

export class ExecuteGetControlPlaneHealth {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly controlPlane: ControlPlaneRepository
  ) {}

  async execute(input: GetControlPlaneHealthInput): Promise<GetControlPlaneHealthOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.hltId();

    // All field names extracted from OpenAPI spec: none
    // Load entity via repository (no ID field - uses input directly, pass correlation ID for response meta)
    const entity = await this.controlPlane.getControlPlaneHealth({ ...input, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found`);
    }

    return entity as GetControlPlaneHealthOutput;
  }
}
