/**
 * LiveBinding DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: strategies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * LiveBinding DTOs
 *
 * DDD: Application DTOs for LiveBinding use cases.
 */

import type { GetLiveBindingParams, RollbackLiveBindingParams, RollbackLiveBindingRequestInput } from "@ordovex/core/strategies/types";

export type GetLiveBindingInput = GetLiveBindingParams;

export type RollbackLiveBindingInput = RollbackLiveBindingParams & RollbackLiveBindingRequestInput;

export type GetLiveBindingOutput = {};

export type RollbackLiveBindingOutput = {};
