/**
 * Strategy DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: strategies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Strategy DTOs
 *
 * DDD: Application DTOs for Strategy use cases.
 */

import type { CreateTradingStrategyRequestInput, GetTradingStrategyParams, ListTradingStrategiesParams } from "@ordovex/core/strategies/types";

export type ListTradingStrategiesInput = ListTradingStrategiesParams;

export type CreateTradingStrategyInput = CreateTradingStrategyRequestInput;

export type GetTradingStrategyInput = GetTradingStrategyParams;

export type ListTradingStrategiesOutput = {};

export type CreateTradingStrategyOutput = {};

export type GetTradingStrategyOutput = {};
