/**
 * AlertRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: concentration
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AlertRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AlertRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  AlertRepository,
} from "@ordovex/services/concentration";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AlertRepositoryDdb } from "./alert-repository.ddb.js";

/**
 * AlertRepositoryAdapter
 *
 * Implements AlertRepository port for infrastructure layer.
 */
export class AlertRepositoryAdapter implements AlertRepository {
  private readonly ddb: AlertRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AlertRepositoryDdb(this.dynamoClient);
  }

  async listConcentrationAlerts(input: Parameters<AlertRepository['listConcentrationAlerts']>[0]): Promise<Awaited<ReturnType<AlertRepository['listConcentrationAlerts']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listConcentrationAlerts(input);
  }

  async createConcentrationAlert(input: Parameters<AlertRepository['createConcentrationAlert']>[0]): Promise<Awaited<ReturnType<AlertRepository['createConcentrationAlert']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createConcentrationAlert(input);
  }
}
