/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: limits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Limits Domain Use Cases
 * 
 * List of all use case names for the limits domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const LIMITS_USE_CASES = [
  "executeApproveLimitRaise",
  "executeGetLimitPackage",
  "executeListLimitPackages",
  "executeProposeLimitRaise",
  "executeSimulateTightestWins",
  "executeUpsertLimitPackage"
] as const;
