/**
 * ExecuteUpsertLimitPackage - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: limits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteUpsertLimitPackage Use Case
 *
 * DDD: Application use case for get Limit.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { UpsertLimitPackageInput, UpsertLimitPackageOutput } from "../dto/limit.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ordovex/services/_shared/index.js";
import type { LimitRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteUpsertLimitPackage {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly limit: LimitRepository
  ) {}

  async execute(input: UpsertLimitPackageInput): Promise<UpsertLimitPackageOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.limId();

    // All field names extracted from OpenAPI spec: deskId, hierarchyLevel, inventorySkewLimit, maxLoss, maxMessageRate, quotingObligation, strategyId, symbol
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).deskId) {
      throw new ValidationError("deskId is required");
    }
    const deskId = (input as any).deskId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.limit.upsertLimitPackage({ deskId: deskId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${deskId}`);
    }

    return entity as UpsertLimitPackageOutput;
  }
}
