/**
 * Repository interface for LiveBinding
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: strategies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  LiveBindingEntity
} from "../models/live-binding.entity.js";
import type {
  LiveBinding
} from "../types/index.js";
/**
 * LiveBindingRepository Interface
 */
export interface LiveBindingRepository extends CreateReadRepository<LiveBindingEntity, LiveBinding, string, Record<string, never>> {

}
