/**
 * Handlers for Approve
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: limits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { LimitsDomainModule } from "../dependencies/limits-ddd.dependencies.js";
import type { ApproveLimitRaiseInput } from "@ordovex/services/limits";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/limits/raises/{limitRaiseId}/approve
 * Operation: approveLimitRaise
 */
export async function approveLimitRaise(
  request: FastifyRequest<{ Params: { limitRaiseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: LimitsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ApproveLimitRaiseInput = {
    limitRaiseId: request.params.limitRaiseId,
  };
  const result = await deps.useCases.approves.create.execute(input);
  return reply.code(200).send(result);
}


