/**
 * Handlers for Raise
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: limits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { LimitsDomainModule } from "../dependencies/limits-ddd.dependencies.js";
import type { ProposeLimitRaiseInput } from "@ordovex/services/limits";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/limits/raises
 * Operation: proposeLimitRaise
 */
export async function proposeLimitRaise(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: LimitsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ProposeLimitRaiseInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.raises.get.execute(input);
  return reply.code(201).send(result);
}


