/**
 * Handlers for SimulateTightest
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: limits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { LimitsDomainModule } from "../dependencies/limits-ddd.dependencies.js";
import type { SimulateTightestWinsInput } from "@ordovex/services/limits";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/limits/simulate-tightest
 * Operation: simulateTightestWins
 */
export async function simulateTightestWins(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { strategyId?: string | string[], symbol?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: LimitsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: SimulateTightestWinsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.simulateTightests.get.execute(input);
  return reply.code(200).send(result);
}


