/**
 * LiveBindingRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: strategies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * LiveBindingRepository Port
 *
 * DDD: Application port for livebindingrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetLiveBindingInput, GetLiveBindingOutput, RollbackLiveBindingInput, RollbackLiveBindingOutput } from "../dto/live-binding.dto";
export interface LiveBindingRepository {
  getLiveBinding(input: GetLiveBindingInput): Promise<GetLiveBindingOutput>;
  rollbackLiveBinding(input: RollbackLiveBindingInput): Promise<RollbackLiveBindingOutput>;
}

export type { GetLiveBindingInput, GetLiveBindingOutput, RollbackLiveBindingInput, RollbackLiveBindingOutput } from "../dto/live-binding.dto";
