/**
 * StrategyRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: strategies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * StrategyRepository Port
 *
 * DDD: Application port for strategyrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateTradingStrategyInput, CreateTradingStrategyOutput, GetTradingStrategyInput, GetTradingStrategyOutput, ListTradingStrategiesInput, ListTradingStrategiesOutput } from "../dto/strategy.dto";
export interface StrategyRepository {
  listTradingStrategies(input: ListTradingStrategiesInput): Promise<ListTradingStrategiesOutput>;
  createTradingStrategy(input: CreateTradingStrategyInput): Promise<CreateTradingStrategyOutput>;
  getTradingStrategy(input: GetTradingStrategyInput): Promise<GetTradingStrategyOutput>;
}

export type { CreateTradingStrategyInput, CreateTradingStrategyOutput, GetTradingStrategyInput, GetTradingStrategyOutput, ListTradingStrategiesInput, ListTradingStrategiesOutput } from "../dto/strategy.dto";
