/**
 * ExecuteGetOrderIntentCheck - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pretrade
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetOrderIntentCheck Use Case
 *
 * DDD: Application use case for get Check.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetOrderIntentCheckInput, GetOrderIntentCheckOutput } from "../dto/check.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ordovex/services/_shared/index.js";
import type { CheckRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetOrderIntentCheck {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly check: CheckRepository
  ) {}

  async execute(input: GetOrderIntentCheckInput): Promise<GetOrderIntentCheckOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.prtId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).orderIntentCheckId) {
      throw new ValidationError("orderIntentCheckId is required");
    }
    const orderintentcheckId = (input as any).orderIntentCheckId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.check.getOrderIntentCheck({ orderIntentCheckId: orderintentcheckId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${orderintentcheckId}`);
    }

    return entity as GetOrderIntentCheckOutput;
  }
}
