/**
 * Routes for Concentration
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: concentration
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getConcentrationSnapshot } from "../handlers/concentration.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function concentrationRoutes(fastify: FastifyInstance) {
  // GET /v1/concentration (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/concentration",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getConcentrationDependenciesForRequest();
        await getConcentrationSnapshot(request, reply, deps);
      });
    }
  );


}
