/**
 * ListStrategy DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: strategies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListTradingStrategiesParams } from "@ordovex/core/strategies";

export function createListStrategyRequest(overrides: Partial<ListTradingStrategiesParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
