/**
 * ExecuteIssueKillOrder - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: kills
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteIssueKillOrder Use Case
 *
 * DDD: Application use case for get Kill.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { IssueKillOrderInput, IssueKillOrderOutput } from "../dto/kill.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ordovex/services/_shared/index.js";
import type { KillRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteIssueKillOrder {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly kill: KillRepository
  ) {}

  async execute(input: IssueKillOrderInput): Promise<IssueKillOrderOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.kilId();

    // All field names extracted from OpenAPI spec: cancelWorking, reason, scope, targetId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).targetId) {
      throw new ValidationError("targetId is required");
    }
    const targetId = (input as any).targetId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.kill.issueKillOrder({ targetId: targetId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${targetId}`);
    }

    return entity as IssueKillOrderOutput;
  }
}
