/**
 * Handlers for Acknowledge
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: telemetry
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { TelemetryDomainModule } from "../dependencies/telemetry-ddd.dependencies.js";
import type { AcknowledgeBreachActionInput } from "@ordovex/services/telemetry";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/telemetry/breaches/{breachActionId}/acknowledge
 * Operation: acknowledgeBreachAction
 */
export async function acknowledgeBreachAction(
  request: FastifyRequest<{ Params: { breachActionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: TelemetryDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: AcknowledgeBreachActionInput = {
    breachActionId: request.params.breachActionId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.acknowledges.get.execute(input);
  return reply.code(200).send(result);
}


