/**
 * ExecuteCreateIncidentPack - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incidents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateIncidentPack Use Case
 *
 * DDD: Application use case for create Pack.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateIncidentPackInput, CreateIncidentPackOutput } from "../dto/pack.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ordovex/services/_shared/index.js";
import type { PackRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateIncidentPack {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly pack: PackRepository
  ) {}

  async execute(input: CreateIncidentPackInput): Promise<CreateIncidentPackOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.incId();

    // All field names extracted from OpenAPI spec: from, strategyId, to
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.strategyId) {
      throw new ValidationError("strategyId is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (incidents domain)
    const entityId = this.idGenerator.incId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.pack.createIncidentPack({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateIncidentPackOutput;
  }
}
