/**
 * ExecuteGetCertification - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: certifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetCertification Use Case
 *
 * DDD: Application use case for get Certification.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetCertificationInput, GetCertificationOutput } from "../dto/certification.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ordovex/services/_shared/index.js";
import type { CertificationRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetCertification {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly certification: CertificationRepository
  ) {}

  async execute(input: GetCertificationInput): Promise<GetCertificationOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.crtId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).certificationId) {
      throw new ValidationError("certificationId is required");
    }
    const certificationId = (input as any).certificationId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.certification.getCertification({ certificationId: certificationId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${certificationId}`);
    }

    return entity as GetCertificationOutput;
  }
}
