/**
 * ExecuteSubmitCertification - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: certifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteSubmitCertification Use Case
 *
 * DDD: Application use case for create Certification.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { SubmitCertificationInput, SubmitCertificationOutput } from "../dto/certification.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ordovex/services/_shared/index.js";
import type { CertificationRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteSubmitCertification {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly certification: CertificationRepository
  ) {}

  async execute(input: SubmitCertificationInput): Promise<SubmitCertificationOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.crtId();

    // All field names extracted from OpenAPI spec: evidenceUri, modelVersionId, requestedLimitPackageId, riskClass, strategyId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.riskClass) {
      throw new ValidationError("riskClass is required");
    }
    if (!input.strategyId) {
      throw new ValidationError("strategyId is required");
    }
    if (!input.modelVersionId) {
      throw new ValidationError("modelVersionId is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (certifications domain)
    const entityId = this.idGenerator.crtId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.certification.submitCertification({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as SubmitCertificationOutput;
  }
}
