/**
 * Telemetry DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: telemetry
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Telemetry DTOs
 *
 * DDD: Application DTOs for Telemetry use cases.
 */

import type { IngestTelemetryRequestInput, ListTelemetrySnapshotsParams } from "@ordovex/core/telemetry/types";

export type IngestTelemetryInput = IngestTelemetryRequestInput;

export type ListTelemetrySnapshotsInput = ListTelemetrySnapshotsParams;

export type IngestTelemetryOutput = {};

export type ListTelemetrySnapshotsOutput = {};
