/**
 * CheckRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pretrade
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CheckRepository Port
 *
 * DDD: Application port for checkrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CheckOrderIntentInput, CheckOrderIntentOutput, GetOrderIntentCheckInput, GetOrderIntentCheckOutput, ListOrderIntentChecksInput, ListOrderIntentChecksOutput } from "../dto/check.dto";
export interface CheckRepository {
  checkOrderIntent(input: CheckOrderIntentInput): Promise<CheckOrderIntentOutput>;
  listOrderIntentChecks(input: ListOrderIntentChecksInput): Promise<ListOrderIntentChecksOutput>;
  getOrderIntentCheck(input: GetOrderIntentCheckInput): Promise<GetOrderIntentCheckOutput>;
}

export type { CheckOrderIntentInput, CheckOrderIntentOutput, GetOrderIntentCheckInput, GetOrderIntentCheckOutput, ListOrderIntentChecksInput, ListOrderIntentChecksOutput } from "../dto/check.dto";
