/**
 * System Routes - Health check and routes listing
 *
 * AUTO-GENERATED by codegen (api_server_system_routes). Do not edit by hand.
 * Domains and routeExamples are derived from discovered api-server domains and
 * each domain's OpenAPI bundled spec.
 */

import type { FastifyInstance } from "fastify";
import {
  getCoreTableName,
  getBaseTableName,
  getAnalyticsTableName,
} from "@ordovex/adapters";
import { getRegisteredRoutes } from "./route-registry.js";

/**
 * Register system routes (health check, routes listing)
 */
export function registerSystemRoutes(fastify: FastifyInstance): void {
  // Health check (public - no auth required)
  fastify.get("/health", { config: { scope: "public" } }, async () => {
    try {
      const coreTable = getCoreTableName();
      const baseTable = getBaseTableName();
      const analyticsTable = getAnalyticsTableName();
      return {
        status: "ok",
        database: "dynamodb",
        tables: {
          core: coreTable,
          base: baseTable,
          analytics: analyticsTable,
        },
      };
    } catch (error: unknown) {
      const errorMessage =
        error instanceof Error ? error.message : String(error);
      fastify.log.warn({ error: errorMessage }, "Health check failed");
      return { status: "error", database: "disconnected", error: errorMessage };
    }
  });

  // Routes listing endpoint (public)
  fastify.get("/routes", { config: { scope: "public" } }, async () => {
    const domains = [
      "certifications", "concentration", "health", "identity", "incidents", "kills", "limits", "pretrade", "strategies", "telemetry"
    ];

    const routeExamples: Record<
      string,
      Array<{ method: string; path: string; description?: string }>
    > = {
      certifications: [{ method: "GET", path: "/v1/certifications" }, { method: "POST", path: "/v1/certifications" }, { method: "GET", path: "/v1/certifications/:certificationId" }, { method: "POST", path: "/v1/certifications/:certificationId/decide" }],
      concentration: [{ method: "GET", path: "/v1/concentration" }, { method: "GET", path: "/v1/concentration/alerts" }, { method: "POST", path: "/v1/concentration/alerts" }],
      health: [{ method: "GET", path: "/v1/health/control-plane" }, { method: "GET", path: "/v1/health/gateways" }],
      identity: [{ method: "GET", path: "/v0/tenants/me/api-keys" }, { method: "POST", path: "/v0/tenants/me/api-keys" }, { method: "GET", path: "/v0/tenants/me/api-keys/:keyId" }, { method: "DELETE", path: "/v0/tenants/me/api-keys/:keyId" }, { method: "GET", path: "/v0/tenants/me/users" }, { method: "POST", path: "/v0/tenants/me/users" }, { method: "GET", path: "/v0/tenants/me/users/:userId" }, { method: "PATCH", path: "/v0/tenants/me/users/:userId" }, { method: "POST", path: "/v0/tenants/me/users/:userId/disable" }, { method: "POST", path: "/v0/tenants/me/users/:userId/enable" }, { method: "POST", path: "/v0/auth/login" }, { method: "GET", path: "/v0/auth/me" }, { method: "PATCH", path: "/v0/auth/me" }, { method: "POST", path: "/v0/auth/refresh" }, { method: "POST", path: "/v0/auth/logout" }],
      incidents: [{ method: "GET", path: "/v1/incidents/packs" }, { method: "POST", path: "/v1/incidents/packs" }, { method: "GET", path: "/v1/incidents/packs/:incidentPackId" }],
      kills: [{ method: "GET", path: "/v1/kills" }, { method: "POST", path: "/v1/kills" }, { method: "GET", path: "/v1/kills/:killOrderId" }, { method: "POST", path: "/v1/kills/:killOrderId/restart" }],
      limits: [{ method: "GET", path: "/v1/limits" }, { method: "PUT", path: "/v1/limits" }, { method: "GET", path: "/v1/limits/:limitPackageId" }, { method: "POST", path: "/v1/limits/raises" }, { method: "POST", path: "/v1/limits/raises/:limitRaiseId/approve" }, { method: "GET", path: "/v1/limits/simulate-tightest" }],
      pretrade: [{ method: "GET", path: "/v1/pretrade/checks" }, { method: "POST", path: "/v1/pretrade/checks" }, { method: "GET", path: "/v1/pretrade/checks/:orderIntentCheckId" }],
      strategies: [{ method: "GET", path: "/v1/strategies" }, { method: "POST", path: "/v1/strategies" }, { method: "GET", path: "/v1/strategies/:strategyId" }, { method: "GET", path: "/v1/strategies/:strategyId/versions" }, { method: "POST", path: "/v1/strategies/:strategyId/versions" }, { method: "GET", path: "/v1/strategies/:strategyId/versions/:modelVersionId" }, { method: "GET", path: "/v1/strategies/:strategyId/live-binding" }, { method: "POST", path: "/v1/strategies/:strategyId/live-binding" }],
      telemetry: [{ method: "GET", path: "/v1/telemetry" }, { method: "POST", path: "/v1/telemetry" }, { method: "GET", path: "/v1/telemetry/breaches" }, { method: "POST", path: "/v1/telemetry/breaches/:breachActionId/acknowledge" }],
    };

    return {
      baseUrl: "http://localhost:4000",
      routePattern: "/orgs/:orgId/{domain}/{resource}",
      authentication:
        "All routes (except /health and /routes) require JWT token in Authorization header",
      domains: domains.sort(),
      routeExamples,
      systemRoutes: [
        { method: "GET", path: "/health", description: "Health check endpoint" },
        { method: "GET", path: "/routes", description: "List available routes" },
      ],
      note: "Replace :orgId with actual organization ID. All domain routes require authentication.",
    };
  });

  // Full route list for API tester page (public)
  fastify.get("/routes/full", { config: { scope: "public" } }, async () => {
    const routes = getRegisteredRoutes();
    const byDomain: Record<
      string,
      Array<{ method: string; path: string }>
    > = {};
    const system: Array<{ method: string; path: string }> = [];
    for (const r of routes) {
      const m = r.path.match(/^\/orgs\/:orgId\/([^/]+)/);
      if (m) {
        const domain = m[1];
        if (!byDomain[domain]) byDomain[domain] = [];
        byDomain[domain].push(r);
      } else {
        system.push(r);
      }
    }
    return {
      baseUrl: "http://localhost:4000",
      total: routes.length,
      system,
      byDomain: Object.keys(byDomain)
        .sort()
        .reduce(
          (acc, k) => ({ ...acc, [k]: byDomain[k] }),
          {} as Record<string, Array<{ method: string; path: string }>>,
        ),
    };
  });
}
