/**
 * Pack DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incidents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Pack DTOs
 *
 * DDD: Application DTOs for Pack use cases.
 */

import type { CreateIncidentPackRequestInput, GetIncidentPackParams, ListIncidentPacksParams } from "@ordovex/core/incidents/types";

export type ListIncidentPacksInput = ListIncidentPacksParams;

export type CreateIncidentPackInput = CreateIncidentPackRequestInput;

export type GetIncidentPackInput = GetIncidentPackParams;

export type ListIncidentPacksOutput = {};

export type CreateIncidentPackOutput = {};

export type GetIncidentPackOutput = {};
