/**
 * Restart DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: kills
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Restart DTOs
 *
 * DDD: Application DTOs for Restart use cases.
 */

import type { AuthoriseRestartParams, AuthoriseRestartRequestInput } from "@ordovex/core/kills/types";

export type AuthoriseRestartInput = AuthoriseRestartParams & AuthoriseRestartRequestInput;

export type AuthoriseRestartOutput = {};
