/**
 * LiveBindingRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: strategies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * LiveBindingRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements LiveBindingRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  LiveBindingRepository,
} from "@ordovex/services/strategies";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { LiveBindingRepositoryDdb } from "./live-binding-repository.ddb.js";

/**
 * LiveBindingRepositoryAdapter
 *
 * Implements LiveBindingRepository port for infrastructure layer.
 */
export class LiveBindingRepositoryAdapter implements LiveBindingRepository {
  private readonly ddb: LiveBindingRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new LiveBindingRepositoryDdb(this.dynamoClient);
  }

  async getLiveBinding(input: Parameters<LiveBindingRepository['getLiveBinding']>[0]): Promise<Awaited<ReturnType<LiveBindingRepository['getLiveBinding']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getLiveBinding(input);
  }

  async rollbackLiveBinding(input: Parameters<LiveBindingRepository['rollbackLiveBinding']>[0]): Promise<Awaited<ReturnType<LiveBindingRepository['rollbackLiveBinding']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.rollbackLiveBinding(input);
  }
}
