/**
 * VersionRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: strategies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * VersionRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements VersionRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  VersionRepository,
} from "@ordovex/services/strategies";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { VersionRepositoryDdb } from "./version-repository.ddb.js";

/**
 * VersionRepositoryAdapter
 *
 * Implements VersionRepository port for infrastructure layer.
 */
export class VersionRepositoryAdapter implements VersionRepository {
  private readonly ddb: VersionRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new VersionRepositoryDdb(this.dynamoClient);
  }

  async listModelVersions(input: Parameters<VersionRepository['listModelVersions']>[0]): Promise<Awaited<ReturnType<VersionRepository['listModelVersions']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listModelVersions(input);
  }

  async submitModelVersion(input: Parameters<VersionRepository['submitModelVersion']>[0]): Promise<Awaited<ReturnType<VersionRepository['submitModelVersion']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.submitModelVersion(input);
  }

  async getModelVersion(input: Parameters<VersionRepository['getModelVersion']>[0]): Promise<Awaited<ReturnType<VersionRepository['getModelVersion']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getModelVersion(input);
  }
}
