/**
 * Check DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pretrade
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Check DTOs
 *
 * DDD: Application DTOs for Check use cases.
 */

import type { CheckOrderIntentRequestInput, GetOrderIntentCheckParams, ListOrderIntentChecksParams } from "@ordovex/core/pretrade/types";

export type CheckOrderIntentInput = CheckOrderIntentRequestInput;

export type ListOrderIntentChecksInput = ListOrderIntentChecksParams;

export type GetOrderIntentCheckInput = GetOrderIntentCheckParams;

export type CheckOrderIntentOutput = {};

export type ListOrderIntentChecksOutput = {};

export type GetOrderIntentCheckOutput = {};
