/**
 * Decide DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: certifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Decide DTOs
 *
 * DDD: Application DTOs for Decide use cases.
 */

import type { DecideCertificationParams, DecideCertificationRequestInput } from "@ordovex/core/certifications/types";

export type DecideCertificationInput = DecideCertificationParams & DecideCertificationRequestInput;

export type DecideCertificationOutput = {};
