/**
 * PackRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incidents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * PackRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements PackRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  PackRepository,
} from "@ordovex/services/incidents";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { PackRepositoryDdb } from "./pack-repository.ddb.js";

/**
 * PackRepositoryAdapter
 *
 * Implements PackRepository port for infrastructure layer.
 */
export class PackRepositoryAdapter implements PackRepository {
  private readonly ddb: PackRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new PackRepositoryDdb(this.dynamoClient);
  }

  async listIncidentPacks(input: Parameters<PackRepository['listIncidentPacks']>[0]): Promise<Awaited<ReturnType<PackRepository['listIncidentPacks']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listIncidentPacks(input);
  }

  async createIncidentPack(input: Parameters<PackRepository['createIncidentPack']>[0]): Promise<Awaited<ReturnType<PackRepository['createIncidentPack']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createIncidentPack(input);
  }

  async getIncidentPack(input: Parameters<PackRepository['getIncidentPack']>[0]): Promise<Awaited<ReturnType<PackRepository['getIncidentPack']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getIncidentPack(input);
  }
}
