/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: concentration
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Concentration Domain Use Cases
 * 
 * List of all use case names for the concentration domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const CONCENTRATION_USE_CASES = [
  "executeCreateConcentrationAlert",
  "executeGetConcentrationSnapshot",
  "executeListConcentrationAlerts"
] as const;
