/**
 * Routes for SimulateTightest
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: limits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { simulateTightestWins } from "../handlers/simulate-tightest.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function simulateTightestRoutes(fastify: FastifyInstance) {
  // GET /v1/limits/simulate-tightest (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/limits/simulate-tightest",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getLimitsDependenciesForRequest();
        await simulateTightestWins(request, reply, deps);
      });
    }
  );


}
