/**
 * Certifications Zod Schemas - Runtime validation schemas
 *
 * Generated by Zod Schemas Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: certifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { makeApi, Zodios, type ZodiosOptions } from '@zodios/core';
import { z } from 'zod';

const submitCertification_Body = z
  .object({
    strategyId: z.string().regex(/^str_[0-9A-HJKMNP-TV-Z]{26}$/),
    modelVersionId: z.string().regex(/^mdl_[0-9A-HJKMNP-TV-Z]{26}$/),
    evidenceUri: z.string().url().optional(),
    riskClass: z.enum(['low', 'medium', 'high']),
    requestedLimitPackageId: z.string().optional(),
  })
  .passthrough();
const decideCertification_Body = z
  .object({
    decision: z.enum(['approve', 'reject']),
    rejectReasons: z.array(z.string()).optional(),
    notes: z.string().optional(),
  })
  .passthrough();

export const schemas: any = {
  submitCertification_Body,
  decideCertification_Body,
};

const endpoints = makeApi([
  {
    method: 'get',
    path: '/v1/certifications',
    alias: 'listCertifications',
    requestFormat: 'json',
    parameters: [
      {
        name: 'cursor',
        type: 'Query',
        schema: z.string().optional(),
      },
      {
        name: 'limit',
        type: 'Query',
        schema: z.number().int().gte(1).lte(200).optional().default(50),
      },
      {
        name: 'status',
        type: 'Query',
        schema: z.enum(['pending', 'certified', 'rejected']).optional(),
      },
      {
        name: 'strategyId',
        type: 'Query',
        schema: z
          .string()
          .regex(/^str_[0-9A-HJKMNP-TV-Z]{26}$/)
          .optional(),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  certificationId: z
                    .string()
                    .regex(/^crt_[0-9A-HJKMNP-TV-Z]{26}$/),
                  strategyId: z.string().regex(/^str_[0-9A-HJKMNP-TV-Z]{26}$/),
                  modelVersionId: z
                    .string()
                    .regex(/^mdl_[0-9A-HJKMNP-TV-Z]{26}$/),
                  evidenceStatus: z.enum(['pending', 'accepted', 'rejected']),
                  evidenceUri: z.string().url().optional(),
                  riskClass: z.enum(['low', 'medium', 'high']),
                  approvedBy: z
                    .string()
                    .regex(/^usr_[0-9A-HJKMNP-TV-Z]{26}$/)
                    .optional(),
                  rejectReasons: z.array(z.string()).optional(),
                  status: z.enum(['pending', 'certified', 'rejected']),
                  createdAt: z.string().datetime({ offset: true }),
                  updatedAt: z.string().datetime({ offset: true }).optional(),
                })
                .passthrough()
            ),
            nextCursor: z.string().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/certifications',
    alias: 'submitCertification',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: submitCertification_Body,
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            certificationId: z.string().regex(/^crt_[0-9A-HJKMNP-TV-Z]{26}$/),
            strategyId: z.string().regex(/^str_[0-9A-HJKMNP-TV-Z]{26}$/),
            modelVersionId: z.string().regex(/^mdl_[0-9A-HJKMNP-TV-Z]{26}$/),
            evidenceStatus: z.enum(['pending', 'accepted', 'rejected']),
            evidenceUri: z.string().url().optional(),
            riskClass: z.enum(['low', 'medium', 'high']),
            approvedBy: z
              .string()
              .regex(/^usr_[0-9A-HJKMNP-TV-Z]{26}$/)
              .optional(),
            rejectReasons: z.array(z.string()).optional(),
            status: z.enum(['pending', 'certified', 'rejected']),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }).optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 422,
        description: `Semantically invalid request (e.g. PACK_EMPTY)`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v1/certifications/:certificationId',
    alias: 'getCertification',
    requestFormat: 'json',
    parameters: [
      {
        name: 'certificationId',
        type: 'Path',
        schema: z.string().regex(/^crt_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            certificationId: z.string().regex(/^crt_[0-9A-HJKMNP-TV-Z]{26}$/),
            strategyId: z.string().regex(/^str_[0-9A-HJKMNP-TV-Z]{26}$/),
            modelVersionId: z.string().regex(/^mdl_[0-9A-HJKMNP-TV-Z]{26}$/),
            evidenceStatus: z.enum(['pending', 'accepted', 'rejected']),
            evidenceUri: z.string().url().optional(),
            riskClass: z.enum(['low', 'medium', 'high']),
            approvedBy: z
              .string()
              .regex(/^usr_[0-9A-HJKMNP-TV-Z]{26}$/)
              .optional(),
            rejectReasons: z.array(z.string()).optional(),
            status: z.enum(['pending', 'certified', 'rejected']),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }).optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/certifications/:certificationId/decide',
    alias: 'decideCertification',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: decideCertification_Body,
      },
      {
        name: 'certificationId',
        type: 'Path',
        schema: z.string().regex(/^crt_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            certificationId: z.string().regex(/^crt_[0-9A-HJKMNP-TV-Z]{26}$/),
            strategyId: z.string().regex(/^str_[0-9A-HJKMNP-TV-Z]{26}$/),
            modelVersionId: z.string().regex(/^mdl_[0-9A-HJKMNP-TV-Z]{26}$/),
            evidenceStatus: z.enum(['pending', 'accepted', 'rejected']),
            evidenceUri: z.string().url().optional(),
            riskClass: z.enum(['low', 'medium', 'high']),
            approvedBy: z
              .string()
              .regex(/^usr_[0-9A-HJKMNP-TV-Z]{26}$/)
              .optional(),
            rejectReasons: z.array(z.string()).optional(),
            status: z.enum(['pending', 'certified', 'rejected']),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }).optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 422,
        description: `Semantically invalid request (e.g. PACK_EMPTY)`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
]);

export const api: any = new Zodios(
  'https://api.ddd-codegen-starter.local',
  endpoints
);

export function createApiClient(baseUrl: string, options?: ZodiosOptions): any {
  return new Zodios(baseUrl, endpoints, options);
}
