/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: health
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Health Domain Use Cases
 * 
 * List of all use case names for the health domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const HEALTH_USE_CASES = [
  "executeGetControlPlaneHealth",
  "executeListGatewayHeartbeats"
] as const;
