/**
 * Handlers index
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: health
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./control-plane.handlers.js";
export * from "./gateway.handlers.js";
