/**
 * Kills DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: kills
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Kills Domain Module - Composition root
 *
 * DDD: Composition root for kills domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  KillRepositoryAdapter,
  RestartRepositoryAdapter,
} from "@ordovex/adapters/kills";
import { getIdGeneratorService } from "@ordovex/adapters";
import type { AdapterDynamoDBClient } from "@ordovex/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteAuthoriseRestart,
  ExecuteGetKillOrder,
  ExecuteIssueKillOrder,
  ExecuteListKillOrders,
} from "@ordovex/services/kills/usecases";
// Ports (interfaces)
import type {
  KillRepository,
  RestartRepository,
} from "@ordovex/services/kills/ports";

export interface KillsDomainModule {
  repos: {
    kills: KillRepository;
    restarts: RestartRepository;
  };
  useCases: {
    kills: {
      get: ExecuteGetKillOrder;
      list: ExecuteListKillOrders;
    };
    restarts: {
      get: ExecuteAuthoriseRestart;
    };
  };
}

export function buildKillsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): KillsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      kills?: KillRepository;
      restarts?: RestartRepository;
    } = {};

    obj.kills = new KillRepositoryAdapter(dynamoClient);
    obj.restarts = new RestartRepositoryAdapter(dynamoClient);
    return {
      kills: obj.kills!,
      restarts: obj.restarts!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    kills: {
      get: new ExecuteGetKillOrder(executionContext, idGenerator, repos.kills),
      list: new ExecuteListKillOrders(executionContext, idGenerator, repos.kills),
    },
    restarts: {
      get: new ExecuteAuthoriseRestart(executionContext, idGenerator, repos.restarts),
    },
  };
  return { repos, useCases: useCases as KillsDomainModule["useCases"] };
}
