/**
 * ExecuteListTelemetrySnapshots - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: telemetry
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListTelemetrySnapshots Use Case
 *
 * DDD: Application use case for list Telemetry.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListTelemetrySnapshotsInput, ListTelemetrySnapshotsOutput } from "../dto/telemetry.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ordovex/services/_shared/index.js";
import type { TelemetryRepository } from "../ports";

export class ExecuteListTelemetrySnapshots {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly telemetry: TelemetryRepository
  ) {}

  async execute(input: ListTelemetrySnapshotsInput): Promise<ListTelemetrySnapshotsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.tlmId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.telemetry.listTelemetrySnapshots({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListTelemetrySnapshotsOutput;
  }
}
