/**
 * ExecuteAcknowledgeBreachAction - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: telemetry
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteAcknowledgeBreachAction Use Case
 *
 * DDD: Application use case for get Acknowledge.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { AcknowledgeBreachActionInput, AcknowledgeBreachActionOutput } from "../dto/acknowledge.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ordovex/services/_shared/index.js";
import type { AcknowledgeRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteAcknowledgeBreachAction {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly acknowledge: AcknowledgeRepository
  ) {}

  async execute(input: AcknowledgeBreachActionInput): Promise<AcknowledgeBreachActionOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.tlmId();

    // All field names extracted from OpenAPI spec: notes
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).breachActionId) {
      throw new ValidationError("breachActionId is required");
    }
    const breachactionId = (input as any).breachActionId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.acknowledge.acknowledgeBreachAction({ breachActionId: breachactionId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${breachactionId}`);
    }

    return entity as AcknowledgeBreachActionOutput;
  }
}
