/**
 * CreateConcentrationAlert handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: concentration
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { createConcentrationAlert } from "@ordovex/api-server/domains/concentration/handlers";
import type { ConcentrationDDDDependencies } from "@ordovex/api-server/domains/concentration";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@ordovex/tests/shared";
import { CONCENTRATION_USE_CASES } from "../__factories__/use-cases.js";

describe("CreateConcentrationAlert", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ConcentrationDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ConcentrationDDDDependencies>(
      CONCENTRATION_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeCreateConcentrationAlert, "execute").mockResolvedValue(useCaseResult);

    await createConcentrationAlert(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeCreateConcentrationAlert.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
