/**
 * Strategies DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: strategies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Strategies Domain Module - Composition root
 *
 * DDD: Composition root for strategies domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  LiveBindingRepositoryAdapter,
  StrategyRepositoryAdapter,
  VersionRepositoryAdapter,
} from "@ordovex/adapters/strategies";
import { getIdGeneratorService } from "@ordovex/adapters";
import type { AdapterDynamoDBClient } from "@ordovex/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateTradingStrategy,
  ExecuteGetLiveBinding,
  ExecuteGetModelVersion,
  ExecuteGetTradingStrategy,
  ExecuteListModelVersions,
  ExecuteListTradingStrategies,
  ExecuteRollbackLiveBinding,
  ExecuteSubmitModelVersion,
} from "@ordovex/services/strategies/usecases";
// Ports (interfaces)
import type {
  LiveBindingRepository,
  StrategyRepository,
  VersionRepository,
} from "@ordovex/services/strategies/ports";

export interface StrategiesDomainModule {
  repos: {
    liveBindings: LiveBindingRepository;
    strategies: StrategyRepository;
    versions: VersionRepository;
  };
  useCases: {
    liveBindings: {
      get: ExecuteRollbackLiveBinding;
    };
    strategies: {
      create: ExecuteCreateTradingStrategy;
      get: ExecuteGetTradingStrategy;
      list: ExecuteListTradingStrategies;
    };
    versions: {
      create: ExecuteSubmitModelVersion;
      get: ExecuteGetModelVersion;
      list: ExecuteListModelVersions;
    };
  };
}

export function buildStrategiesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): StrategiesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      liveBindings?: LiveBindingRepository;
      strategies?: StrategyRepository;
      versions?: VersionRepository;
    } = {};

    obj.liveBindings = new LiveBindingRepositoryAdapter(dynamoClient);
    obj.strategies = new StrategyRepositoryAdapter(dynamoClient);
    obj.versions = new VersionRepositoryAdapter(dynamoClient);
    return {
      liveBindings: obj.liveBindings!,
      strategies: obj.strategies!,
      versions: obj.versions!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    liveBindings: {
      get: new ExecuteRollbackLiveBinding(executionContext, idGenerator, repos.liveBindings),
    },
    strategies: {
      create: new ExecuteCreateTradingStrategy(executionContext, idGenerator, repos.strategies),
      get: new ExecuteGetTradingStrategy(executionContext, idGenerator, repos.strategies),
      list: new ExecuteListTradingStrategies(executionContext, idGenerator, repos.strategies),
    },
    versions: {
      create: new ExecuteSubmitModelVersion(executionContext, idGenerator, repos.versions),
      get: new ExecuteGetModelVersion(executionContext, idGenerator, repos.versions),
      list: new ExecuteListModelVersions(executionContext, idGenerator, repos.versions),
    },
  };
  return { repos, useCases: useCases as StrategiesDomainModule["useCases"] };
}
