/**
 * Gateway DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: health
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Gateway DTOs
 *
 * DDD: Application DTOs for Gateway use cases.
 */

import type { ListGatewayHeartbeatsParams } from "@ordovex/core/health/types";

export type ListGatewayHeartbeatsInput = ListGatewayHeartbeatsParams;

export type ListGatewayHeartbeatsOutput = {};
