/**
 * Routes for Version
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: strategies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getModelVersion, listModelVersions, submitModelVersion } from "../handlers/version.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function versionRoutes(fastify: FastifyInstance) {
  // GET /v1/strategies/{strategyId}/versions (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/strategies/:strategyId/versions",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { strategyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getStrategiesDependenciesForRequest();
        await listModelVersions(request, reply, deps);
      });
    }
  );


  // POST /v1/strategies/{strategyId}/versions (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/strategies/:strategyId/versions",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { strategyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getStrategiesDependenciesForRequest();
        await submitModelVersion(request, reply, deps);
      });
    }
  );


  // GET /v1/strategies/{strategyId}/versions/{modelVersionId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/strategies/:strategyId/versions/:modelVersionId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { strategyId: string, modelVersionId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getStrategiesDependenciesForRequest();
        await getModelVersion(request, reply, deps);
      });
    }
  );


}
