/**
 * CertificationRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: certifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CertificationRepository Port
 *
 * DDD: Application port for certificationrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetCertificationInput, GetCertificationOutput, ListCertificationsInput, ListCertificationsOutput, SubmitCertificationInput, SubmitCertificationOutput } from "../dto/certification.dto";
export interface CertificationRepository {
  listCertifications(input: ListCertificationsInput): Promise<ListCertificationsOutput>;
  submitCertification(input: SubmitCertificationInput): Promise<SubmitCertificationOutput>;
  getCertification(input: GetCertificationInput): Promise<GetCertificationOutput>;
}

export type { GetCertificationInput, GetCertificationOutput, ListCertificationsInput, ListCertificationsOutput, SubmitCertificationInput, SubmitCertificationOutput } from "../dto/certification.dto";
