/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: telemetry
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { breachRoutes } from "./breach.routes.js";
export { telemetryRoutes } from "./telemetry.routes.js";
export { acknowledgeRoutes } from "./acknowledge.routes.js";
