/**
 * GetCertification DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: certifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetCertificationParams } from "@ordovex/core/certifications";

export function createGetCertificationRequest(overrides: Partial<GetCertificationParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
