/**
 * Limits DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: limits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Limits Domain Module - Composition root
 *
 * DDD: Composition root for limits domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ApproveRepositoryAdapter,
  LimitRepositoryAdapter,
  RaiseRepositoryAdapter,
  SimulateTightestRepositoryAdapter,
} from "@ordovex/adapters/limits";
import { getIdGeneratorService } from "@ordovex/adapters";
import type { AdapterDynamoDBClient } from "@ordovex/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteApproveLimitRaise,
  ExecuteGetLimitPackage,
  ExecuteListLimitPackages,
  ExecuteProposeLimitRaise,
  ExecuteSimulateTightestWins,
  ExecuteUpsertLimitPackage,
} from "@ordovex/services/limits/usecases";
// Ports (interfaces)
import type {
  ApproveRepository,
  LimitRepository,
  RaiseRepository,
  SimulateTightestRepository,
} from "@ordovex/services/limits/ports";

export interface LimitsDomainModule {
  repos: {
    approves: ApproveRepository;
    limits: LimitRepository;
    raises: RaiseRepository;
    simulateTightests: SimulateTightestRepository;
  };
  useCases: {
    approves: {
      create: ExecuteApproveLimitRaise;
    };
    limits: {
      get: ExecuteGetLimitPackage;
      list: ExecuteListLimitPackages;
    };
    raises: {
      get: ExecuteProposeLimitRaise;
    };
    simulateTightests: {
      get: ExecuteSimulateTightestWins;
    };
  };
}

export function buildLimitsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): LimitsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      approves?: ApproveRepository;
      limits?: LimitRepository;
      raises?: RaiseRepository;
      simulateTightests?: SimulateTightestRepository;
    } = {};

    obj.approves = new ApproveRepositoryAdapter(dynamoClient);
    obj.limits = new LimitRepositoryAdapter(dynamoClient);
    obj.raises = new RaiseRepositoryAdapter(dynamoClient);
    obj.simulateTightests = new SimulateTightestRepositoryAdapter(dynamoClient);
    return {
      approves: obj.approves!,
      limits: obj.limits!,
      raises: obj.raises!,
      simulateTightests: obj.simulateTightests!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    approves: {
      create: new ExecuteApproveLimitRaise(executionContext, idGenerator, repos.approves),
    },
    limits: {
      get: new ExecuteGetLimitPackage(executionContext, idGenerator, repos.limits),
      list: new ExecuteListLimitPackages(executionContext, idGenerator, repos.limits),
    },
    raises: {
      get: new ExecuteProposeLimitRaise(executionContext, idGenerator, repos.raises),
    },
    simulateTightests: {
      get: new ExecuteSimulateTightestWins(executionContext, idGenerator, repos.simulateTightests),
    },
  };
  return { repos, useCases: useCases as LimitsDomainModule["useCases"] };
}
