/**
 * AcknowledgeRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: telemetry
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AcknowledgeRepository Port
 *
 * DDD: Application port for acknowledgerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { AcknowledgeBreachActionInput, AcknowledgeBreachActionOutput } from "../dto/acknowledge.dto";
export interface AcknowledgeRepository {
  acknowledgeBreachAction(input: AcknowledgeBreachActionInput): Promise<AcknowledgeBreachActionOutput>;
}

export type { AcknowledgeBreachActionInput, AcknowledgeBreachActionOutput } from "../dto/acknowledge.dto";
