/**
 * TelemetryRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: telemetry
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * TelemetryRepository Port
 *
 * DDD: Application port for telemetryrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { IngestTelemetryInput, IngestTelemetryOutput, ListTelemetrySnapshotsInput, ListTelemetrySnapshotsOutput } from "../dto/telemetry.dto";
export interface TelemetryRepository {
  ingestTelemetry(input: IngestTelemetryInput): Promise<IngestTelemetryOutput>;
  listTelemetrySnapshots(input: ListTelemetrySnapshotsInput): Promise<ListTelemetrySnapshotsOutput>;
}

export type { IngestTelemetryInput, IngestTelemetryOutput, ListTelemetrySnapshotsInput, ListTelemetrySnapshotsOutput } from "../dto/telemetry.dto";
