/**
 * GetKillOrder handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: kills
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getKillOrder } from "@ordovex/api-server/domains/kills/handlers";
import type { KillsDDDDependencies } from "@ordovex/api-server/domains/kills";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@ordovex/tests/shared";
import { KILLS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetKillOrder", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: KillsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<KillsDDDDependencies>(
      KILLS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetKillOrder, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { killOrderId: entity.id };

    await getKillOrder(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetKillOrder.execute).toHaveBeenCalledWith(expect.objectContaining({ killOrderId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { killOrderId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetKillOrder, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getKillOrder(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
