/**
 * IssueKillOrder handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: kills
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { issueKillOrder } from "@ordovex/api-server/domains/kills/handlers";
import type { KillsDDDDependencies } from "@ordovex/api-server/domains/kills";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@ordovex/tests/shared";
import { KILLS_USE_CASES } from "../__factories__/use-cases.js";

describe("IssueKillOrder", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: KillsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<KillsDDDDependencies>(
      KILLS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeIssueKillOrder, "execute").mockResolvedValue(useCaseResult);

    await issueKillOrder(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeIssueKillOrder.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
