/**
 * ControlPlaneRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: health
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ControlPlaneRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ControlPlaneRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ControlPlaneRepository,
} from "@ordovex/services/health";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ControlPlaneRepositoryDdb } from "./control-plane-repository.ddb.js";

/**
 * ControlPlaneRepositoryAdapter
 *
 * Implements ControlPlaneRepository port for infrastructure layer.
 */
export class ControlPlaneRepositoryAdapter implements ControlPlaneRepository {
  private readonly ddb: ControlPlaneRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ControlPlaneRepositoryDdb(this.dynamoClient);
  }

  async getControlPlaneHealth(input: Parameters<ControlPlaneRepository['getControlPlaneHealth']>[0]): Promise<Awaited<ReturnType<ControlPlaneRepository['getControlPlaneHealth']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getControlPlaneHealth(input);
  }
}
