/**
 * Pretrade DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pretrade
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Pretrade Domain Module - Composition root
 *
 * DDD: Composition root for pretrade domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  CheckRepositoryAdapter,
} from "@ordovex/adapters/pretrade";
import { getIdGeneratorService } from "@ordovex/adapters";
import type { AdapterDynamoDBClient } from "@ordovex/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCheckOrderIntent,
  ExecuteGetOrderIntentCheck,
  ExecuteListOrderIntentChecks,
} from "@ordovex/services/pretrade/usecases";
// Ports (interfaces)
import type {
  CheckRepository,
} from "@ordovex/services/pretrade/ports";

export interface PretradeDomainModule {
  repos: {
    checks: CheckRepository;
  };
  useCases: {
    checks: {
      get: ExecuteGetOrderIntentCheck;
      list: ExecuteListOrderIntentChecks;
    };
  };
}

export function buildPretradeDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): PretradeDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      checks?: CheckRepository;
    } = {};

    obj.checks = new CheckRepositoryAdapter(dynamoClient);
    return {
      checks: obj.checks!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    checks: {
      get: new ExecuteGetOrderIntentCheck(executionContext, idGenerator, repos.checks),
      list: new ExecuteListOrderIntentChecks(executionContext, idGenerator, repos.checks),
    },
  };
  return { repos, useCases: useCases as PretradeDomainModule["useCases"] };
}
