/**
 * Routes for Kill
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: kills
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getKillOrder, issueKillOrder, listKillOrders } from "../handlers/kill.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function killRoutes(fastify: FastifyInstance) {
  // POST /v1/kills (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/kills",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getKillsDependenciesForRequest();
        await issueKillOrder(request, reply, deps);
      });
    }
  );


  // GET /v1/kills (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/kills",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getKillsDependenciesForRequest();
        await listKillOrders(request, reply, deps);
      });
    }
  );


  // GET /v1/kills/{killOrderId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/kills/:killOrderId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { killOrderId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getKillsDependenciesForRequest();
        await getKillOrder(request, reply, deps);
      });
    }
  );


}
