/**
 * Routes for Restart
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: kills
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { authoriseRestart } from "../handlers/restart.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function restartRoutes(fastify: FastifyInstance) {
  // POST /v1/kills/{killOrderId}/restart (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/kills/:killOrderId/restart",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { killOrderId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getKillsDependenciesForRequest();
        await authoriseRestart(request, reply, deps);
      });
    }
  );


}
