/**
 * RaiseRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: limits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RaiseRepository Port
 *
 * DDD: Application port for raiserepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ProposeLimitRaiseInput, ProposeLimitRaiseOutput } from "../dto/raise.dto";
export interface RaiseRepository {
  proposeLimitRaise(input: ProposeLimitRaiseInput): Promise<ProposeLimitRaiseOutput>;
}

export type { ProposeLimitRaiseInput, ProposeLimitRaiseOutput } from "../dto/raise.dto";
