/**
 * SimulateTightestRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: limits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SimulateTightestRepository Port
 *
 * DDD: Application port for simulatetightestrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { SimulateTightestWinsInput, SimulateTightestWinsOutput } from "../dto/simulate-tightest.dto";
export interface SimulateTightestRepository {
  simulateTightestWins(input: SimulateTightestWinsInput): Promise<SimulateTightestWinsOutput>;
}

export type { SimulateTightestWinsInput, SimulateTightestWinsOutput } from "../dto/simulate-tightest.dto";
