/**
 * ExecuteGetModelVersion - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: strategies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetModelVersion Use Case
 *
 * DDD: Application use case for get Version.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetModelVersionInput, GetModelVersionOutput } from "../dto/version.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ordovex/services/_shared/index.js";
import type { VersionRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetModelVersion {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly version: VersionRepository
  ) {}

  async execute(input: GetModelVersionInput): Promise<GetModelVersionOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.strId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).strategyId) {
      throw new ValidationError("strategyId is required");
    }
    const strategyId = (input as any).strategyId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.version.getModelVersion({ strategyId: strategyId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${strategyId}`);
    }

    return entity as GetModelVersionOutput;
  }
}
