/**
 * ExecuteListTradingStrategies - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: strategies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListTradingStrategies Use Case
 *
 * DDD: Application use case for list Strategy.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListTradingStrategiesInput, ListTradingStrategiesOutput } from "../dto/strategy.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ordovex/services/_shared/index.js";
import type { StrategyRepository } from "../ports";

export class ExecuteListTradingStrategies {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly strategy: StrategyRepository
  ) {}

  async execute(input: ListTradingStrategiesInput): Promise<ListTradingStrategiesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.strId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.strategy.listTradingStrategies({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListTradingStrategiesOutput;
  }
}
