/**
 * Handlers for Check
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: pretrade
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { PretradeDomainModule } from "../dependencies/pretrade-ddd.dependencies.js";
import type { CheckOrderIntentInput, GetOrderIntentCheckInput, ListOrderIntentChecksInput } from "@ordovex/services/pretrade";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/pretrade/checks
 * Operation: checkOrderIntent
 */
export async function checkOrderIntent(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: PretradeDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CheckOrderIntentInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.checks.get.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/pretrade/checks
 * Operation: listOrderIntentChecks
 */
export async function listOrderIntentChecks(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], strategyId?: string | string[], result?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: PretradeDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListOrderIntentChecksInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.checks.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for GET /v1/pretrade/checks/{orderIntentCheckId}
 * Operation: getOrderIntentCheck
 */
export async function getOrderIntentCheck(
  request: FastifyRequest<{ Params: { orderIntentCheckId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: PretradeDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetOrderIntentCheckInput = {
    orderIntentCheckId: request.params.orderIntentCheckId,
  };
  const result = await deps.useCases.checks.get.execute(input);
  return reply.code(200).send(result);
}


