/**
 * CertificationRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: certifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CertificationRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements CertificationRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  CertificationRepository,
} from "@ordovex/services/certifications";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { CertificationRepositoryDdb } from "./certification-repository.ddb.js";

/**
 * CertificationRepositoryAdapter
 *
 * Implements CertificationRepository port for infrastructure layer.
 */
export class CertificationRepositoryAdapter implements CertificationRepository {
  private readonly ddb: CertificationRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new CertificationRepositoryDdb(this.dynamoClient);
  }

  async listCertifications(input: Parameters<CertificationRepository['listCertifications']>[0]): Promise<Awaited<ReturnType<CertificationRepository['listCertifications']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listCertifications(input);
  }

  async submitCertification(input: Parameters<CertificationRepository['submitCertification']>[0]): Promise<Awaited<ReturnType<CertificationRepository['submitCertification']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.submitCertification(input);
  }

  async getCertification(input: Parameters<CertificationRepository['getCertification']>[0]): Promise<Awaited<ReturnType<CertificationRepository['getCertification']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getCertification(input);
  }
}
