/**
 * Routes for Certification
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: certifications
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getCertification, listCertifications, submitCertification } from "../handlers/certification.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function certificationRoutes(fastify: FastifyInstance) {
  // GET /v1/certifications (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/certifications",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getCertificationsDependenciesForRequest();
        await listCertifications(request, reply, deps);
      });
    }
  );


  // POST /v1/certifications (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/certifications",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getCertificationsDependenciesForRequest();
        await submitCertification(request, reply, deps);
      });
    }
  );


  // GET /v1/certifications/{certificationId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/certifications/:certificationId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { certificationId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getCertificationsDependenciesForRequest();
        await getCertification(request, reply, deps);
      });
    }
  );


}
