/**
 * ApproveLimitRaise handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: limits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { approveLimitRaise } from "@ordovex/api-server/domains/limits/handlers";
import type { LimitsDDDDependencies } from "@ordovex/api-server/domains/limits";
import { createCreateApproveRequest } from "@ordovex/factories/limits";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@ordovex/tests/shared";
import { LIMITS_USE_CASES } from "../__factories__/use-cases.js";

describe("ApproveLimitRaise", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: LimitsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<LimitsDDDDependencies>(
      LIMITS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = createCreateApproveRequest();
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeApproveLimitRaise, "execute").mockResolvedValue(useCaseResult);

    await approveLimitRaise(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeApproveLimitRaise.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
