/**
 * Alert DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: concentration
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Alert DTOs
 *
 * DDD: Application DTOs for Alert use cases.
 */

import type { CreateConcentrationAlertRequestInput, ListConcentrationAlertsParams } from "@ordovex/core/concentration/types";

export type ListConcentrationAlertsInput = ListConcentrationAlertsParams;

export type CreateConcentrationAlertInput = CreateConcentrationAlertRequestInput;

export type ListConcentrationAlertsOutput = {};

export type CreateConcentrationAlertOutput = {};
