/**
 * Handlers for LiveBinding
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: strategies
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { StrategiesDomainModule } from "../dependencies/strategies-ddd.dependencies.js";
import type { GetLiveBindingInput, RollbackLiveBindingInput } from "@ordovex/services/strategies";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/strategies/{strategyId}/live-binding
 * Operation: getLiveBinding
 */
export async function getLiveBinding(
  request: FastifyRequest<{ Params: { strategyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: StrategiesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetLiveBindingInput = {
    strategyId: request.params.strategyId,
  };
  const result = await deps.useCases.liveBindings.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/strategies/{strategyId}/live-binding
 * Operation: rollbackLiveBinding
 */
export async function rollbackLiveBinding(
  request: FastifyRequest<{ Params: { strategyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: StrategiesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RollbackLiveBindingInput = {
    strategyId: request.params.strategyId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.liveBindings.get.execute(input);
  return reply.code(200).send(result);
}


