/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: limits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./approve-repository.ddb.js";
export * from "./limit-repository.ddb.js";
export * from "./raise-repository.ddb.js";
export * from "./simulate-tightest-repository.ddb.js";
export * from "./approve-repository.adapter.js";
export * from "./limit-repository.adapter.js";
export * from "./raise-repository.adapter.js";
export * from "./simulate-tightest-repository.adapter.js";
