/**
 * SimulateTightestRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: limits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SimulateTightestRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements SimulateTightestRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  SimulateTightestRepository,
} from "@ordovex/services/limits";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { SimulateTightestRepositoryDdb } from "./simulate-tightest-repository.ddb.js";

/**
 * SimulateTightestRepositoryAdapter
 *
 * Implements SimulateTightestRepository port for infrastructure layer.
 */
export class SimulateTightestRepositoryAdapter implements SimulateTightestRepository {
  private readonly ddb: SimulateTightestRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new SimulateTightestRepositoryDdb(this.dynamoClient);
  }

  async simulateTightestWins(input: Parameters<SimulateTightestRepository['simulateTightestWins']>[0]): Promise<Awaited<ReturnType<SimulateTightestRepository['simulateTightestWins']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.simulateTightestWins(input);
  }
}
