/**
 * KillRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: kills
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * KillRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements KillRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  KillRepository,
} from "@ordovex/services/kills";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { KillRepositoryDdb } from "./kill-repository.ddb.js";

/**
 * KillRepositoryAdapter
 *
 * Implements KillRepository port for infrastructure layer.
 */
export class KillRepositoryAdapter implements KillRepository {
  private readonly ddb: KillRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new KillRepositoryDdb(this.dynamoClient);
  }

  async listKillOrders(input: Parameters<KillRepository['listKillOrders']>[0]): Promise<Awaited<ReturnType<KillRepository['listKillOrders']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listKillOrders(input);
  }

  async issueKillOrder(input: Parameters<KillRepository['issueKillOrder']>[0]): Promise<Awaited<ReturnType<KillRepository['issueKillOrder']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.issueKillOrder(input);
  }

  async getKillOrder(input: Parameters<KillRepository['getKillOrder']>[0]): Promise<Awaited<ReturnType<KillRepository['getKillOrder']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getKillOrder(input);
  }
}
