/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: incidents
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Incidents Domain Use Cases
 * 
 * List of all use case names for the incidents domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const INCIDENTS_USE_CASES = [
  "executeCreateIncidentPack",
  "executeGetIncidentPack",
  "executeListIncidentPacks"
] as const;
