/**
 * Limits Zod Schemas - Runtime validation schemas
 *
 * Generated by Zod Schemas Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: limits
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import { makeApi, Zodios, type ZodiosOptions } from '@zodios/core';
import { z } from 'zod';

const upsertLimitPackage_Body = z
  .object({
    strategyId: z
      .string()
      .regex(/^str_[0-9A-HJKMNP-TV-Z]{26}$/)
      .optional(),
    deskId: z.string().optional(),
    hierarchyLevel: z.enum(['firm', 'desk', 'strategy', 'symbol']),
    maxLoss: z.number(),
    maxMessageRate: z.number().int().optional(),
    inventorySkewLimit: z.number().optional(),
    quotingObligation: z.string().optional(),
    symbol: z.string().optional(),
  })
  .passthrough();
const proposeLimitRaise_Body = z
  .object({
    limitPackageId: z.string().regex(/^lim_[0-9A-HJKMNP-TV-Z]{26}$/),
    proposedMaxLoss: z.number(),
    proposedMaxMessageRate: z.number().int().optional(),
    reason: z.string().optional(),
  })
  .passthrough();

export const schemas: any = {
  upsertLimitPackage_Body,
  proposeLimitRaise_Body,
};

const endpoints = makeApi([
  {
    method: 'get',
    path: '/v1/limits',
    alias: 'listLimitPackages',
    requestFormat: 'json',
    parameters: [
      {
        name: 'cursor',
        type: 'Query',
        schema: z.string().optional(),
      },
      {
        name: 'limit',
        type: 'Query',
        schema: z.number().int().gte(1).lte(200).optional().default(50),
      },
      {
        name: 'hierarchyLevel',
        type: 'Query',
        schema: z.enum(['firm', 'desk', 'strategy', 'symbol']).optional(),
      },
      {
        name: 'strategyId',
        type: 'Query',
        schema: z
          .string()
          .regex(/^str_[0-9A-HJKMNP-TV-Z]{26}$/)
          .optional(),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            items: z.array(
              z
                .object({
                  limitPackageId: z
                    .string()
                    .regex(/^lim_[0-9A-HJKMNP-TV-Z]{26}$/),
                  strategyId: z
                    .string()
                    .regex(/^str_[0-9A-HJKMNP-TV-Z]{26}$/)
                    .optional(),
                  deskId: z.string().optional(),
                  hierarchyLevel: z.enum([
                    'firm',
                    'desk',
                    'strategy',
                    'symbol',
                  ]),
                  maxLoss: z.number(),
                  maxMessageRate: z.number().int().optional(),
                  inventorySkewLimit: z.number().optional(),
                  quotingObligation: z.string().optional(),
                  symbol: z.string().optional(),
                  createdAt: z.string().datetime({ offset: true }),
                  updatedAt: z.string().datetime({ offset: true }).optional(),
                })
                .passthrough()
            ),
            nextCursor: z.string().optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'put',
    path: '/v1/limits',
    alias: 'upsertLimitPackage',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: upsertLimitPackage_Body,
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            limitPackageId: z.string().regex(/^lim_[0-9A-HJKMNP-TV-Z]{26}$/),
            strategyId: z
              .string()
              .regex(/^str_[0-9A-HJKMNP-TV-Z]{26}$/)
              .optional(),
            deskId: z.string().optional(),
            hierarchyLevel: z.enum(['firm', 'desk', 'strategy', 'symbol']),
            maxLoss: z.number(),
            maxMessageRate: z.number().int().optional(),
            inventorySkewLimit: z.number().optional(),
            quotingObligation: z.string().optional(),
            symbol: z.string().optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }).optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 422,
        description: `Semantically invalid request (e.g. PACK_EMPTY)`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v1/limits/:limitPackageId',
    alias: 'getLimitPackage',
    requestFormat: 'json',
    parameters: [
      {
        name: 'limitPackageId',
        type: 'Path',
        schema: z.string().regex(/^lim_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            limitPackageId: z.string().regex(/^lim_[0-9A-HJKMNP-TV-Z]{26}$/),
            strategyId: z
              .string()
              .regex(/^str_[0-9A-HJKMNP-TV-Z]{26}$/)
              .optional(),
            deskId: z.string().optional(),
            hierarchyLevel: z.enum(['firm', 'desk', 'strategy', 'symbol']),
            maxLoss: z.number(),
            maxMessageRate: z.number().int().optional(),
            inventorySkewLimit: z.number().optional(),
            quotingObligation: z.string().optional(),
            symbol: z.string().optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }).optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/limits/raises',
    alias: 'proposeLimitRaise',
    requestFormat: 'json',
    parameters: [
      {
        name: 'body',
        type: 'Body',
        schema: proposeLimitRaise_Body,
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            limitRaiseId: z.string().regex(/^lir_[0-9A-HJKMNP-TV-Z]{26}$/),
            limitPackageId: z.string().regex(/^lim_[0-9A-HJKMNP-TV-Z]{26}$/),
            proposedMaxLoss: z.number(),
            proposedMaxMessageRate: z.number().int().optional(),
            status: z.enum(['proposed', 'approved', 'rejected', 'applied']),
            proposedBy: z
              .string()
              .regex(/^usr_[0-9A-HJKMNP-TV-Z]{26}$/)
              .optional(),
            approvedBy: z
              .string()
              .regex(/^usr_[0-9A-HJKMNP-TV-Z]{26}$/)
              .optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }).optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 422,
        description: `Semantically invalid request (e.g. PACK_EMPTY)`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'post',
    path: '/v1/limits/raises/:limitRaiseId/approve',
    alias: 'approveLimitRaise',
    requestFormat: 'json',
    parameters: [
      {
        name: 'limitRaiseId',
        type: 'Path',
        schema: z.string().regex(/^lir_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
      {
        name: 'Idempotency-Key',
        type: 'Header',
        schema: z.string().min(1).max(128),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            limitRaiseId: z.string().regex(/^lir_[0-9A-HJKMNP-TV-Z]{26}$/),
            limitPackageId: z.string().regex(/^lim_[0-9A-HJKMNP-TV-Z]{26}$/),
            proposedMaxLoss: z.number(),
            proposedMaxMessageRate: z.number().int().optional(),
            status: z.enum(['proposed', 'approved', 'rejected', 'applied']),
            proposedBy: z
              .string()
              .regex(/^usr_[0-9A-HJKMNP-TV-Z]{26}$/)
              .optional(),
            approvedBy: z
              .string()
              .regex(/^usr_[0-9A-HJKMNP-TV-Z]{26}$/)
              .optional(),
            createdAt: z.string().datetime({ offset: true }),
            updatedAt: z.string().datetime({ offset: true }).optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
      {
        status: 404,
        description: `Resource not found`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
  {
    method: 'get',
    path: '/v1/limits/simulate-tightest',
    alias: 'simulateTightestWins',
    requestFormat: 'json',
    parameters: [
      {
        name: 'strategyId',
        type: 'Query',
        schema: z.string().regex(/^str_[0-9A-HJKMNP-TV-Z]{26}$/),
      },
      {
        name: 'symbol',
        type: 'Query',
        schema: z.string().optional(),
      },
    ],
    response: z
      .object({
        data: z
          .object({
            strategyId: z.string().regex(/^str_[0-9A-HJKMNP-TV-Z]{26}$/),
            symbol: z.string().optional(),
            effectiveMaxLoss: z.number(),
            effectiveMaxMessageRate: z.number().int().optional(),
            winningLevel: z.enum(['firm', 'desk', 'strategy', 'symbol']),
            generatedAt: z.string().datetime({ offset: true }),
            createdAt: z.string().datetime({ offset: true }).optional(),
            updatedAt: z.string().datetime({ offset: true }).optional(),
          })
          .passthrough(),
        meta: z
          .object({
            requestId: z.string().uuid(),
            correlationId: z.string(),
            generatedAt: z.string().datetime({ offset: true }),
          })
          .partial()
          .passthrough()
          .optional(),
      })
      .passthrough(),
    errors: [
      {
        status: 401,
        description: `Missing or invalid API key`,
        schema: z
          .object({
            type: z.string().url(),
            title: z.string(),
            status: z.number().int(),
            detail: z.string(),
            instance: z.string().url(),
            code: z.string(),
          })
          .partial()
          .passthrough(),
      },
    ],
  },
]);

export const api: any = new Zodios(
  'https://api.ddd-codegen-starter.local',
  endpoints
);

export function createApiClient(baseUrl: string, options?: ZodiosOptions): any {
  return new Zodios(baseUrl, endpoints, options);
}
