/**
 * Handlers for Kill
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: kills
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { KillsDomainModule } from "../dependencies/kills-ddd.dependencies.js";
import type { GetKillOrderInput, IssueKillOrderInput, ListKillOrdersInput } from "@ordovex/services/kills";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/kills
 * Operation: listKillOrders
 */
export async function listKillOrders(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], scope?: string | string[], targetId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: KillsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListKillOrdersInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.kills.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/kills
 * Operation: issueKillOrder
 */
export async function issueKillOrder(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: KillsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: IssueKillOrderInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.kills.get.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/kills/{killOrderId}
 * Operation: getKillOrder
 */
export async function getKillOrder(
  request: FastifyRequest<{ Params: { killOrderId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: KillsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetKillOrderInput = {
    killOrderId: request.params.killOrderId,
  };
  const result = await deps.useCases.kills.get.execute(input);
  return reply.code(200).send(result);
}


